/**
 * Insight recommendation from the backend's intelligent prompt generator.
 * Contains rich contextual information for visualization generation.
 */
export interface InsightRecommendation {
  /** Chart type (bar, line, pie, scatter, table, etc.) */
  type?: string;
  /** X-axis column name */
  x?: string | null;
  /** Y-axis column name */
  y?: string | null;
  /** Group by column for segmentation */
  groupBy?: string | null;
  /** Aggregation method (sum, avg, count, etc.) */
  aggregation?: string | null;
  /** Confidence score 0-1 */
  confidence?: number;
  /** Human-readable reasoning for this recommendation */
  reason?: string;
  /** Suggested title for the visualization */
  title_suggestion?: string;
  /** Also accept 'title' from backend */
  title?: string;
  /** Short description of what this visualization shows */
  description?: string;
  /** 
   * Rich, contextual prompt for AI visualization generation.
   * Generated by backend's PromptGeneratorService with full data context.
   */
  prompt?: string;
  /** Unique key for deduplication */
  key?: string;
}
